### ISSUE TITLE
LoginError: 'server says: NeedsBrowser'

### ISSUE THREAD

**Issue by wetterfroschdus** [NoMore201/googleplay-api#10]
Using python 3 (3.4.3) i get this:

    python3 test.py
    
    Logging in with email and password
    
    Traceback (most recent call last):
      File "test.py", line 14, in <module>
        server.login(EMAIL, PASSWD, None, None)
      File "/home/wetterfroschdus/googleplay-api/gpapi/googleplay.py", line 198, in login
        raise LoginError("server says: " + params["error"])
    gpapi.googleplay.LoginError: "server says: NeedsBrowser"

Any ideas? I actually never used a phone on the account I'm trying to use. Could it be related to that?

**Comment by wetterfroschdus** [comment]
Nevermind, fixed it by doing this:
https://accounts.google.com/b/0/DisplayUnlockCaptcha

**Comment by NoMore201** [comment]
Never had this response, probably one of the google security checks

**Comment by wetterfroschdus** [comment]
Yeah it is, you'd have to use the link i posted everytime you want to activate a new device for a Google account.

**Comment by NoMore201** [comment]
I'm almost sure I didn't have to activate any of my test accounts, probably google trusts me :P

Anyway, I think gpapi should intercept that error and provide a more clear message about what to do, I'm reopening the issue as an enhancement.

**Comment by matlink** [comment]
Most of the time, this mean either a verification step is asked by Google (check your email to prove your identity) or because 2FA has been enable.
I found something interesting: enable 2FA, generate an application password and use it instead your real password. It works like a charm :D
