### ISSUE TITLE
Change Location without changing the IP

### ISSUE THREAD

**Issue by chandralegend** [NoMore201/googleplay-api#129]
I want to know whether it is possible to get the list of top free apps of some other country without changing the IP.

**Comment by mn4r** [comment]
@chandralegend are you find solution?

**Comment by iamDonkey** [comment]
> I think you can add a header:
> 
> ```
> Accept-Language: es-AR
> ```

i think it gives response in localised text only not actually change the location.

**Comment by mn4r** [comment]
@89z @iamDonkey yes, its only change language, not country.
