### ISSUE TITLE
Change default device

### ISSUE THREAD

**Issue by NoMore201** [NoMore201/googleplay-api#14]
Since angler (Google Nexus 6P) is reaching its end-of-life date, default device should be updated with a newer one, maybe a Google Pixel:
https://github.com/yeriomin/play-store-api/blob/master/src/main/resources/device-sailfish.properties

**Comment by matlink** [comment]
Be careful of the architecture of the default device.

**Comment by NoMore201** [comment]
I choose `bacon` (OnePlus 1) as default device, for the following reasons:

- Very wide diffusion: [LOS stats](https://stats.lineageos.org/)
- Supports the most common platforms: `armeabi-v7a, armeabi`
- I own a OnePlus 1, so I'm able to update device information in case something stops working.

If you have a better solution, let me know.

**Comment by matlink** [comment]
That sounds reasonable. I'll need to change default for gplaycli too then.

**Comment by muzzyrost** [comment]
Do you generate device options for device.properties by some script using build.prop file?

**Comment by matlink** [comment]
I used .properties files in the play-store-api repo of @yeriomin

**Comment by NoMore201** [comment]
All devices taken from here [0], then I updated some strings for `bacon` using my device.
If you want to add/update one, it's not so difficult. You could use mitmproxy [1] and listen to a play store session on you phone (the trickiest part is to install the certificate on android as a system certificate).

[0] https://github.com/yeriomin/play-store-api/tree/master/src/main/resources
[1] https://mitmproxy.org/
