### ISSUE TITLE
Download old app versions

### ISSUE THREAD

**Issue by dschm1dt** [NoMore201/googleplay-api#165]
Hello,
I tried to download old app versions (I know the old version code), still, I always get the newest... I was wondering if someone had the same issue or if there were changes by google?

**Comment by 89z** [comment]
please provide example app

**Comment by dschm1dt** [comment]
For example when I try to download the following app
* id: com.android.chrome
* version code: 418312060
it downloads the apk with the version code: 524912620.

**Comment by 89z** [comment]
In some cases, you can change the `versionCode` in the `User-Agent` to fix the issue, but in other cases you need to use `X-Dfe-Device-Id` from an older device for it to work. I will continue working on this

**Comment by 89z** [comment]
OK I have successfully pulled `com.android.chrome` as a single APK. However I have to go through 1800 lines of ProtoBuf to figure out what triggers is, probably something simple. Will try to post update tomorrow

**Comment by 89z** [comment]
https://github.com/89z/googleplay/issues/107

**Comment by 89z** [comment]
OK I am able to get even older versions:

~~~
> googleplay -a com.android.chrome -s -v 418310171
POST https://android.googleapis.com/auth
GET https://play-fe.googleapis.com/fdfe/delivery?doc=com.android.chrome&vc=418310171
GET https://play.googleapis.com/download/by-token/download?token=AOTCm0QcgeTi7KAGLcOT4Fyg36KamvcDkg9t2Dk3cS8AbQzuXTYELMmDeWFRCSctSAo8znkIiSDPm6_nui8Brfb1NYGo3kM1okP23PlR2iarc4jFQ4YzQbC9vISt82T6D96IFsTWoGUOd8YbVrNQHe6m5ql2l4hQDTw0WlDFX1P7RXfPfdlL_lXrg8OvHPGOoI1lWsXQXbpQ6VZLQ5vXI1ZZmrFrRK2pXpY__vUhCRuuY71ADuPMPvZHmi1k7Qw_Ii1DqhfAg2WLcbrKiMe8hJooeeO521D8c-_5RjX8YAI33oEvmV69fcnXJiZL8kavULk3_Ji_byAJBRcMDF_pQJDo-qmoM6xalgsmVs9fLRjLfp-jGStry-QZmb6AIEaOg2EShq1OD6Bo_oTAj1SBhCoXr90t6Lbz&cpn=KBsHgNF9KsmbR1tk
Create com.android.chrome-418310171.apk
7.80%   9.17 megabyte   9.17 megabyte/s
~~~

but you have to be very careful about what version number you choose. For example, the number I chose above is for x86 Android 7, which matches the device I am requesting with.
