### ISSUE TITLE
Help in Covering more PlayStore endpoints (adding features/functionality)

### ISSUE THREAD

**Issue by erev0s** [NoMore201/googleplay-api#168]
if I have understood well how this api works, is that it covers specific endpoints for which the `googleplay.proto` already has the correct protobuf details so the responses can be converted to a JSON readable format.

Then this means that for some of the endpoints that are not covered we need to have the proper `googleplay.proto` in order to read them.

If I am not mistaken, one example of such an endpoint is the `GET /fdfe/getDetailsStream?doc={package_name}&ps=`.

Given that I am very new to protobuf and how the play store retrieves the information it has, could maybe someone with more experience validate whether the above is correct or not?

and the big question is, if indeed an updated `googleplay.proto` is required to read some of the other endpoints, how do we make that? or is there already an existing project that has done that ?

hopefully someone can help out, as I am interested in this project and I would like to contribute to further improve it

**Comment by Warflop** [comment]
Hey @erev0s, I think the proto of this project is related to this one:

https://github.com/yeriomin/play-store-api

I mean:

https://github.com/NoMore201/googleplay-api/blob/master/googleplay.proto
https://github.com/yeriomin/play-store-api/blob/master/src/main/proto/GooglePlay.proto

**Comment by ghost** [comment]
why do you care about that endpoint? what does it offer that the current ones do not?
