### ISSUE TITLE
Dynamically change locale and timezone

### ISSUE THREAD

**Issue by NoMore201** [NoMore201/googleplay-api#19]
It would be nice to change locale and timezone dynamically, rather than having default values.
Maybe during startup it could be parsed from system (https://docs.python.org/3.6/library/locale.html), and then it would be nice having some functions to change it.

**Comment by matlink** [comment]
Function `locale.getlocale()` seems the one to use.

**Comment by NoMore201** [comment]
Implemented in e1acc14. Since I can't find an easy way to get timezone from system (needs to work for every platform), default to `Europe/Berlin`
