### ISSUE TITLE
search: IndexError: list index out of range

### ISSUE THREAD

**Issue by dizzy666** [NoMore201/googleplay-api#21]
```
>>> server.search('phongit.quickreboot', 1, None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/gpapi/googleplay.py", line 315, in search
    if cluster.doc[0].containerMetadata.nextPageUrl != "":
IndexError: list index out of range
```

**Comment by NoMore201** [comment]
I can reproduce the issue, basically I didn't consider the case when the query didn't return any result. It should be fixed with commit 11128cd, let me know

**Comment by dizzy666** [comment]
This commit return always 'No result' in playmaker search.
OT: What is the best way to sniff the query in a docker environment for debugging?

**Comment by NoMore201** [comment]
If you go on play store and insert your query, you will get no result
https://play.google.com/store/search?q=phongit.quickreboot&c=apps
the problem is your query, google doesn't like dots in a query maybe. Try separating keywords with a space, but in this case the app you are searching doesn't really exist.

**Comment by dizzy666** [comment]
Dots are not the problem it work for 250 other apps to search query by packageid.

**Comment by NoMore201** [comment]
True, then the problem is that app doesn't exist since i can't find it in results:
https://play.google.com/store/search?q=quickreboot&c=apps
https://play.google.com/store/search?q=phongit&c=apps

**Comment by dizzy666** [comment]
The app exists or was existing in the past. I have installed it on a device with play store. Will check the device later.

https://play.google.com/store/apps/details?id=phongit.quickreboot&hl=en show me:
```
Sorry! This content is not available in your country yet.
We're working to bring the content you love to more countries as quickly as possible.
Please check back again soon.
```

**Comment by dizzy666** [comment]
Magically closed or just a google problem ?
New response:
`We're sorry, the requested URL was not found on this server.`
