### ISSUE TITLE
ValueError: Unknown format code 'x' for object of type 'str'

### ISSUE THREAD

**Issue by rehmatworks** [NoMore201/googleplay-api#29]
Thanks for this amazing code. While trying to login with gsfid and token, I get an error ```ValueError: Unknown format code 'x' for object of type 'str'``` (Python 2.7.12). Am I getting this error due to my Python version? If yes, then is there any fix for the version 2.7.x? Thanks in advance.

p.s. I tested with Python Python 3.5.2 and still get ```ValueError: Unknown format code 'x' for object of type 'str'``` error

**Comment by matlink** [comment]
Gsfid needs to be in int, you should convert it with int(gsfid,16). Also gsfid hex string should not have 0x at start.

**Comment by rehmatworks** [comment]
@matlink Thanks for your input. I'll try this.
