### ISSUE TITLE
gpapi: Security check is needed

### ISSUE THREAD

**Issue by michaelhku2002** [NoMore201/googleplay-api#30]
Hi all,

I just used the API for about a month or two in the Ubuntu server for downloading APKs for security checking. In the early December, it still worked. But when I just wanted to modify my program and then run again, it shows the followings:

File "/[my program folder]/googleplay.py", line xxx, in login
    raise LoginError("Security check is needed, try to visit "
googleplay.LoginError: 'Security check is needed, try to visit https://accounts.google.com/b/0/DisplayUnlockCaptcha to unlock, or setup an app-specific password'

I just provided the GOOGLE_LOGIN and GOOGLE_PASSWORD for the first login. Then I tried to unlock using browser, but it still does not work. So what happened? Thanks!

**Comment by rehmatworks** [comment]
Are you using an app-specific password or the general one?

**Comment by michaelhku2002** [comment]
@rehmatworks it should be the general one

**Comment by matlink** [comment]
You can enable 2FA for this account and generate an app password for it.

**Comment by michaelhku2002** [comment]
@matlink do you mean I replace the password with the generated app password and then the api can login  using this without generating it next time I run the program with calling this API?

**Comment by michaelhku2002** [comment]
Alright, I understood what happened. Thanks @matlink 's comment, and I just used the generated app password as the GOOGLE_PASSWORD and then logged in successfully. Thanks for your help!
