### ISSUE TITLE
Push to pypi

### ISSUE THREAD

**Issue by matlink** [NoMore201/googleplay-api#4]
Is it possible to push it to pypi?

**Comment by NoMore201** [comment]
There is still the original project there https://pypi.python.org/pypi/googleplay-api.
There is also a fork of the original one, with a slightly different name. https://pypi.python.org/pypi/googleplayapi
Should i change the name?

**Comment by matlink** [comment]
They are deprecated. If you think you'll support your library for a long time, I would like to use it from now.
So yes, push your fork with an alternate name, `gpapi` sounds great since that's what you used in your repo.

**Comment by NoMore201** [comment]
Done. Here it is: https://pypi.python.org/pypi?:action=display&name=gpapi&version=0.1.2
