### ISSUE TITLE
Support download of obb files

### ISSUE THREAD

**Issue by NoMore201** [NoMore201/googleplay-api#6]
Application like `com.haikugamesco.escapeasylum` requires the download of additional .obb files

**Comment by matlink** [comment]
in `delivery()` method, the additional file can be accessed by `resObj.payload.deliveryResponse.appDeliveryData.additionalFile`

**Comment by NoMore201** [comment]
@matlink Nice! Since it's possible to download obb files, I'm wondering now if the delivery function should return a list. Probably a list of dictionaries like this:

```
{'docId': 'com.some.thing',
 'data': <bytes>,
 'additionalData': [ {'name': 'somefile.obb',
                               'data': <bytes>}, ... ]
```

**Comment by matlink** [comment]
That's sound right to me.

**Comment by NoMore201** [comment]
Working on it on branch obb-files. I omitted name for expansion files, since it is not provided by google, and as the documentation [0] states, it should follow this format:

    [main|patch].<expansion-version>.<package-name>.obb

It is better to let the application using gpapi build the string, using information provided like this:

    {'docId': 'com.some.thing',
     'data': <bytes>,
     'additionalData': [ {'type': 'main',
                          'versionCode': 99,
                          'data': <bytes>}]

[0] https://developer.android.com/google/play/expansion-files.html

**Comment by muzzyrost** [comment]
Maps.me

**Comment by NoMore201** [comment]
Done in 0.2.4
