### ISSUE TITLE
How can I download multiple apk files at the same time?

### ISSUE THREAD

**Issue by zuiyangqingzhou** [NoMore201/googleplay-api#60]
I started multiple threads to download multiple apk files, but when I downloaded a file and prompted "Segmentation fault", is it that "google play" restricts an account to download only one file at the same time? I don't know, I hope to get help, I am grateful.

**Comment by NoMore201** [comment]
When you use play-store on a phone and download multiple apps, it will handle one download at a time, so I guess it's not possible by API design
