### ISSUE TITLE
How to create device profile from a real device?

### ISSUE THREAD

**Issue by Bnaya** [NoMore201/googleplay-api#61]
First, thank you for your amazing project!

I have a given device, And i want to create device.properties entry for it.
What is the most simple way to do so?
Is there any script that can do that?
Thanks!

**Comment by matlink** [comment]
Maybe using an emulator.

**Comment by NoMore201** [comment]
@korangu I don't think it is possible if you don't own a device. Also, if you want to add a device using @matlink tool or anything you want, please contribute it to play-store-api [1], which is the project where properties are fetched in gpapi

[1] https://github.com/yeriomin/play-store-api/tree/master/src/main/resources
