### ISSUE TITLE
where I can find the  the gsfId and the authSubToken?

### ISSUE THREAD

**Issue by kaloon2009** [NoMore201/googleplay-api#65]
Hello @NoMore201 you mentioned that I have to " save the gsfId and the authSubToken for next login". where I can find  gsfId and the authSubToken? in order to save it

Thanks you

**Comment by VishalSharmavj** [comment]
A easy way is to print both of them when signing in via mail id and save them for later use.

**Comment by NoMore201** [comment]
As @VishalSharmavj said:
https://github.com/NoMore201/googleplay-api/blob/588b17eb7c90a37adbb2cc35d948d43ad0f4c6f4/test/test.py#L17-L19
