### ISSUE TITLE
Getting error for some apps: Google Play purchases are not supported in your country. Unfortunately you will not be able to complete purchases.

### ISSUE THREAD

**Issue by ahm786** [NoMore201/googleplay-api#66]
Hi,

When I attempt to download certain apps, it returns the following error although the app is free:

> Google Play purchases are not supported in your country. Unfortunately you will not be able to complete purchases.

Examples:
- com.ubisoft.accovenant
- com.ubisoft.hungrysharkheroes
- com.netmarble.kof

How can this issue get fixed? There are a lot of apps that get this error.

**Full error log:**

> Attempting to download com.ubisoft.accovenant
> 
> Traceback (most recent call last):
>   File "gp/obb_download.py", line 83, in <module>
>     fl = server.download(docId, expansion_files=True)
>   File "/var/www/html/gp/gpapi/googleplay.py", line 661, in download
>     raise RequestError(response.commands.displayErrorMessage)
> gpapi.googleplay.RequestError: 'Google Play purchases are not supported in your country. Unfortunately you will not be able to complete purchases.'

**Comment by darkash** [comment]
the app is geo-locked, try using tunneling and see if it works

**Comment by ahm786** [comment]
> the app is geo-locked, try using tunneling and see if it works

Can you refer me to a documentation or an example regarding this? Haven't heard or done "tunneling" before

**Comment by korangu** [comment]
when initializing googleplay class

pass the proxy dict like this
proxy= {'http': 'http://user:pass@10.10.1.10:3128/'}

refer https://github.com/NoMore201/googleplay-api/blob/master/gpapi/googleplay.py#L67

**Comment by sweisgerber-dev** [comment]
You could also use VPN tunneling on your host, where the gpapi applications runs on.
For tests and exploration you could try e.g.: https://www.softether.org/ (not the best performance sometimes). Then you wouldn't have to use a proxy.
But there are dozens of free and non-free VPN tunneling applications available.

**Comment by darkash** [comment]
> > the app is geo-locked, try using tunneling and see if it works
> 
> Can you refer me to a documentation or an example regarding this? Haven't heard or done "tunneling" before

I didn't look at the documentation before since I used this library as the dependency of other library, instead I used VPN as described by @sweisgerber-dev on the post above to bypass the country restriction
