### ISSUE TITLE
How to Fix 'Your device is not compatible with this item.' Error?

### ISSUE THREAD

**Issue by ahm786** [NoMore201/googleplay-api#70]
Hi,

I get the following error when I attempt to download **com.tekoia.sure.activities** APK file: 'Your device is not compatible with this item'

**Full error log:**

> Traceback (most recent call last):
>   File "gp/download.py", line 78, in <module>
>     fl = server.download(docId)
>   File "gpapi/googleplay.py", line 661, in download
>     raise RequestError(response.commands.displayErrorMessage)
> gpapi.googleplay.RequestError: 'Your device is not compatible with this item.'

**App link:**

[https://play.google.com/store/apps/details?id=com.tekoia.sure.activities](https://play.google.com/store/apps/details?id=com.tekoia.sure.activities)

How can I choose the the compatible device to be used? Or how can this issue be fixed?

Thanks!

**Comment by korangu** [comment]
try 
Samsung Galaxy Nexus (api23)

server = GooglePlayAPI('en_IN', 'Asia/Kolkata','maguro')

check other devices here https://github.com/NoMore201/googleplay-api/blob/master/gpapi/device.properties

**Comment by sweisgerber-dev** [comment]
@ahm786 
Pixel Phone & Pixel 2 are also good devices with a huge compatibility. I prefer those devices.

Once you logged in with a specific device config, and especially if you re-login with your stored token,
you should keep the same device spec also for the re-login.
I made some experiments w/ switching the device and hade the same problems/error messages as you dexcribe

**Comment by NoMore201** [comment]
My suggestion is to use a popular supported device for your architecture, like pixel 1 & 2 for arm64 or bacon/hammerhead for arm.

Also be aware that device properties are fetched directly from play-store-api [1]. If you want to add definitions for a particular device, please contribute to that repository.

[1] https://github.com/yeriomin/play-store-api/tree/master/src/main/resources
