### ISSUE TITLE
googleplay.proto: File does not reside within any path specified

### ISSUE THREAD

**Issue by rehmatworks** [NoMore201/googleplay-api#85]
Since the last release, the installation breaks. I've installed protobuf-compiler on my system (Ubuntu 18) and when I try to run `setup.py build`, I get the following error:

```
googleplay.proto: File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think).
```

Do I need to perform any additional configurations? And just curious to know is building the project locally really important? What does this improve over the previous installation?

Thank you for your great efforts!

**Comment by rehmatworks** [comment]
When I run the command manually without providing the absolute path, it works:
`protoc --python_out=/nvmea/data/misc/googleplay-api/gpapi googleplay.proto`

This solves the issue for me but you may need to check if something else also faces this issue. Seems strange as even if I provide the path manually (without using `CURRENT_DIR` variable), still that doesn't work.

**Comment by Amagicians** [comment]
Hi, have you ever met the bad authentication error? I copied the sample code given in the ReadMe and changed the account and password into my own google account, but I kept getting "Bad Authentication" errors. I have built googleplay_bp2 and added gpapi into the python lib.

**Comment by NoMore201** [comment]
This is related to commit e5e60b8. Protobuf class will be generated with a `python setup.py build` call.

This is explained also in the README.md https://github.com/NoMore201/googleplay-api/blob/master/README.md#build
