### ISSUE TITLE
 raise Exception("You should install protobuf compiler")

### ISSUE THREAD

**Issue by x011** [NoMore201/googleplay-api#96]
windows 10 - python 3.6.8 with protobuf3 installed?
How to fix this?

**Comment by Cornul11** [comment]
Download the latest version of protoc for your platform, specifically Windows 10 from here, and install it: https://github.com/protocolbuffers/protobuf/releases

**Comment by NoMore201** [comment]
Problem should be fixed now. If you have the protobuf directory in your PATH environment variable it should work (on every OS)
